// livro-servidor/clientes/livros-react/src/LivroLista.tsx
import React, { useState, useEffect } from "react";
import { ControleLivro}   from "./controle/ControleLivros";
import { ControleEditora }  from "./controle/ControleEditora";
import { Livro } from "./modelo/Livro";

import Button from "./components/Button";
import Menu from "./components/Menu";
import axios from 'axios';


type PropsLinhaLivro = {
  livro: Livro;
  acervo: ControleLivro;
  carregando: () => void;
};

type Props = {
  livros: ControleLivro;
};



const LinhaLivro = ({ acervo, livro, carregando }: PropsLinhaLivro) => {
  const editora = new ControleEditora();

  const handleExcluirClick = () => {
    acervo.excluir(String(livro.codigo))
      .then(() => {
        setCarregado(false);
      })
      .catch((error) => {
        console.error(error);
      });
  };




  return (
    <>
      <tr>
        <th scope="row">
          <p>{livro.titulo}</p>

          <Button 
            type="button"
            className="btn btn-danger btn-sm" 
            onClick={handleExcluirClick}
          >
            Excluir
          </Button>

 


        </th>
        <td>{livro.resumo}</td>
        <td>
          {editora.getNomeEditora(livro.codEditora).map((nomeEditora) => {
            return nomeEditora.nome;
          })}
        </td>
        <td>
          <ul>
            {livro.autores.map((nome) => {
              return <li>{nome}</li>;
            })}
          </ul>
        </td>
      </tr>
    </>
  );
};

export function LivroLista({ livros }: Props) {
  const [listaLivros, setlistaLivros] = useState<Livro[]>(livros.obterLivros());
  const [carregando, setCarregando] = useState<boolean>(false);

  useEffect(() => {
    setCarregando(true);
    axios.get(livros.obterLivros())
      .then(response => {
        setlistaLivros(response.data);
        setCarregando(false);
      })
      .catch(error => console.error(error));
  }, [carregando]);

  return (
    <>
      <Menu />
      <main className="container">
        <h1>Catalogo de Livros</h1>
        <table className="table table-striped">
          <thead>
            <tr>
              <th scope="col">Título</th>
              <th scope="col">Resumo</th>
              <th scope="col">Editora</th>
              <th scope="col">Autores</th>
            </tr>
          </thead>
          <tbody>
            {listaLivros.map((livro) => {
              return (
                <LinhaLivro
                  key={String(livro.codigo)}
                  livro={livro}
                  carregando={setCarregando}
                  acervo={livros}
                />
              );
            })}
          </tbody>
        </table>
      </main>
    </>
  );
}

// livro-servidor/clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Editora } from '../editora';
import { Livro } from '../livro';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent {

public editoras: Array<Editora> = []
public livros: Array<Livro> = []

constructor (
  private servEditora: ControleEditoraService,
  private servLivros: ControleLivrosService,
  private router: Router
  ){}

  ngOnInit(): void {

    this.servEditora.getEditoras().subscribe((editoras) => {
      this.editoras = editoras
    }
    )

    this.servLivros.obterLivros().subscribe((livros)=>{
      this.livros = livros;
    })



    }

    excluir = (codigo: number) => {
      this.servLivros.excluir(codigo);
      this.servLivros.obterLivros().subscribe((livros)=>{
        this.livros = livros;
    })}

    obterNome = (codEditora: number) => {
      return this.servEditora.getNomeEditora(codEditora).map((nomeEditora) => {
        return nomeEditora.nome;
      })};

    }

  

<main class="container">
  <h1>Catálogo de Livros</h1>
  <table class="table table-striped">
    <tr>
      <thead>
        <tr>
          <th>Titulo</th>
          <th>Resumo</th>
          <th>Editora</th>
          <th>Autores</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let livro of livros">
          <td>
            {{livro.titulo}}
            <br>
            <button type="button" class="btn btn-danger btn-sm" (click)="excluir(livro.codigo)">
              Excluir
            </button>

          </td>
          <td>{{livro.resumo}}</td>
          <td>{{obterNome(livro.codEditora)}}</td>
          <td>
            <ul>
              <li *ngFor="let autor of livro.autores">{{autor}}</li>
            </ul>
          </td>
        </tr>
      </tbody>
