// livro-servidor/clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Editora } from '../editora';
import { Livro } from '../livro';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent {

  public autoresForm: string = '';
  public editoras: Array<Editora> = [];
  public livro: Livro = new Livro(0, 0, "titulo", "resumo", ["fulanos"])

  constructor (
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
    ){}

  ngOnInit(): void {
    this.servEditora.getEditoras().subscribe((editoras) => {
      this.editoras = editoras
    }
    )

  }

  incluir = () => {
    this.livro.autores = this.autoresForm.replace(',', '\n').split('\n');
    console.log(this.autoresForm)
    this.servLivros.incluir(this.livro)
    this.router.navigateByUrl('/lista');

  }



}




<main class="container mt-5">
  <h1>Cadastro de Livro</h1>
  <form (submit)="incluir()" ngNativeValidate>
    <div class="form-group">
      <label for="titulo">Título</label>
      <input type="text" class="form-control" id="titulo" name="titulo" required [(ngModel)]="livro.titulo">
    </div>
    <div class="form-group">
      <label for="resumo">Resumo</label>
      <textarea class="form-control" id="resumo" name="resumo" rows="3" [(ngModel)]="livro.resumo"></textarea>
    </div>
    <div class="form-group">
      <label for="editora">Editora</label>
      <select class="form-control" id="editora" name="editora" required [(ngModel)]="livro.codEditora">
        <option value="" disabled selected>Selecione a Editora</option>
        <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
      </select>
    </div>
    <div class="form-group">
      <label for="autores">Autores</label>
      <textarea class="form-control" id="autores" name="autores" rows="3" [(ngModel)]="autoresForm"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Salvar Dados</button>
  </form>
</main>

// livro-servidor/clientes/livros-next/pages/LivroDados.tsx
import type { NextPage } from "next";
import React from "react";
import { useState } from "react";
import { Menu } from "@/componentes/Menu";
import { Livro } from "../classes/modelo/Livro";
import { ControleEditora } from "../classes/controle/ControleEditora";
import { ControleLivro } from "@/classes/controle/ControleLivros";
import { Editora } from "../classes/modelo/Editora";
import { useRouter } from "next/router";
import Button from "@/componentes/Button";
import Head from "next/head";



const LivroDados: NextPage = () => {
  const [titulo, setTitulo] = useState<string>("");
  const [resumo, setResumo] = useState<string>("");
  const [editora, setEditora] = useState<number>(1);

  const router = useRouter();
  const editoras = new ControleEditora();
  const livros = new ControleLivro()


  function incluir(event: React.FormEvent) {
    event.preventDefault();

    const novoLivro = new Livro(1, editora, titulo, resumo, []);
    livros.incluir(novoLivro);
    router.push("./LivroLista");
  }

  return (
    <>
      
        
  
        <Menu/>
      <main className="container">
        <h1>Dados Livro</h1>
        <form onSubmit={(event) => incluir(event)}>
          
          <div className="form-group">
            <label htmlFor="titulo">Título</label>
            <input
              id="titulo"
              type="text"
              value={titulo}
              onChange={(event) => setTitulo(event.target.value)}
              className="form-control"
              placeholder="Titulo do livro"
            />
          </div>
          

          
          <div className="form-group mt-2">
            <label htmlFor="resumo">Resumo</label>
            <textarea
              id="resumo"
              value={resumo}
              onChange={(event) => setResumo(event.target.value)}
              className="form-control"
              rows={3}
            ></textarea>
          </div>
         

          <div className="form-group mt-2">
            
            <label htmlFor="editora">Editora</label>
            <select
              id="editora"
              value={editora}
              onChange={(event) => {
                setEditora(Number(event.target.value));
              }}
              className="form-select"
            >

              {editoras.getEditoras().map((editora) => {
                return (
                  <option value={Number(editora.codEditora)}>{editora.nome}</option>
                );
              })}
            </select>

          </div>
          
          <div className="form-group mt-2">
            <label htmlFor="autores">Autores (1 por linha)</label>
            <textarea id="autores" className="form-control" rows={3}></textarea>
          </div>
         

          <Button className="btn btn-primary mt-2">Salvar dados</Button>
          
        </form>
      </main>
    </>
  );
}

export default LivroDados;
